### ISSUE TITLE
Array.prototype.sort does not sort numeric values ascending

### ISSUE THREAD

**Issue by ajafff** [basementuniverse/stats#1]
I see that this library uses `Array.prototype.sort` to sort the input array. Without a comparator function it will convert all array elements to string and sorts them by char code. E.g. `("100" < "2") === true`

therefore some functions don't work as expected:

```ts
const {median} = require("@basementuniverse/stats")
console.log(median([1, 2, 100])); // logs: 100, expected: 2
```

To fix this, make sure to pass in a comparator: `arr.sort((a, b) => a -b)`

**Comment by gordon-winkel** [comment]
Thanks! I have fixed this in 280bdb6
